---
openapi: 3.0.0
info:
  title: Entso-e Transparency Restful API
  description: "## &#128679; (Beta version) \n\n # &#128226; You asked for it and we listened! \n With this document our aim is to provide a developer-friendly technical documentation for Entso-e Transparency Platform Restful API. This documentation is prepared according to openAPI specification (OAS) standards.  \n\n # &#10071; Please read before going any further:\n\n * In order to separate the data items we have introduced so-called resource names (i.e. '/api<b>/6.1.A</b>'). This made us stick with the OAS standards. Please keep in mind that we have only one resource ('/api') and remove the trailing part (i.e. '/6.1.A') while making a http request. \n * This document is only covering GET method since it is very commonly used / preferred by end users. \n\n # &#128071; We would like to hear from you."
  contact:
    name: Transparency Team
    url: https://web-api.tp.entsoe.eu
    email: transparency@entsoe.eu
  version: "0.1"
servers:
- url: https://web-api.tp.entsoe.eu
paths:
  /api/6.1.A:
    get:
      tags:
      - 6.1.A Actual Total Load
      description: "# &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#9757; /api<s>/6.1.B</s>    \nActual total load per bidding zone per market time unit, the total load being defined as equal to the sum of power generated by plants on both TSO/DSO networks, from which is deduced  - the balance (export-import) of exchanges on interconnections between neighbouring bidding zones. - the power absorbed by energy storage resources. The information shall be published at the latest H+1 after the end of the operating period. \n\n <b>Example web browser get method (replace &#128071;MYTOKEN with yours)</b> \n\n <a href=\"https://web-api.tp.entsoe.eu/api?securityToken=MYTOKEN&documentType=A65&processType=A16&outBiddingZone_Domain=10YCZ-CEPS-----N&periodStart=201512312300&periodEnd=201612312300\">https://web-api.tp.entsoe.eu/api?securityToken=MYTOKEN&documentType=A65&processType=A16&outBiddingZone_Domain=10YCZ-CEPS-----N&periodStart=201512312300&periodEnd=201612312300</a>"
      parameters:
      - name: securityToken
        in: query
        description: In order to get web api security token you must first register to the <a href= 'https://transparency.entsoe.eu'>https://transparency.entsoe.eu</a> website. Then after successfully logging in you must go to 'my account settings' and create a web api security token.
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: 1fbe3cd7-0055-4188-bb37-4c6728687251
      - name: outBiddingZone_Domain
        in: query
        description: The possible EIC codes can be found at https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/ url. Please select 'EIC Type Code' as 'All Codes' and filter 'FUNCTION' as 'Bidding Zone'
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: 10YCZ-CEPS-----N
      - name: documentType
        in: query
        description: The document type describes the principal characteristic of the document. For each data item this value might change.
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - A65
      - name: processType
        in: query
        description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - A16
      - name: periodStart
        in: query
        description: Time is always expressed in UTC. Pattern is yyyyMMddHHmm
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: "201601010000"
      - name: periodEnd
        in: query
        description: Time is always expressed in UTC. Pattern is yyyyMMddHHmm
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: "201601010000"
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: 'components/schemas/GL_MarketDocument.yaml#/GL_MarketDocument'
        "400":
          description: Invalid query attributes or parameters
          content:
            application/xml:
              schema:
                $ref: 'components/schemas/Acknowledgement_MarketDocument.yaml#/Acknowledgement_MarketDocument'
components:
  parameters:
    securityToken:
      name: securityToken
      in: query
      description: In order to get web api security token you must first register to the <a href= 'https://transparency.entsoe.eu'>https://transparency.entsoe.eu</a> website. Then after successfully logging in you must go to 'my account settings' and create a web api security token.
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: 1fbe3cd7-0055-4188-bb37-4c6728687251
    outBiddingZoneDomain:
      name: outBiddingZone_Domain
      in: query
      description: The possible EIC codes can be found at https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/ url. Please select 'EIC Type Code' as 'All Codes' and filter 'FUNCTION' as 'Bidding Zone'
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: 10YCZ-CEPS-----N
    inDomain:
      name: in_Domain
      in: query
      description: The possible EIC codes can be found at https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/ url. Please select 'EIC Type Code' as 'All Codes' and filter 'FUNCTION' as 'control area'
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: 10YCZ-CEPS-----N
    documentType61A:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A65
    processType61A:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType61B:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A65
    processType61B:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType61C:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A65
    processType61C:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType61D:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A65
    processType61D:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A32
    documentType61E:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A65
    processType61E:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A33
    documentType81:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A70
    processType81:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A33
    documentType141A:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A68
    processType141A:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A33
    documentType161D:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A72
    processType161D:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType161BC:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A74
        - A75
    processType161BC:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType161A:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A73
    processType161A:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A16
    documentType141C:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A71
    processType141C:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A01
    documentType141D:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A69
    processType141D:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A01
        - A40
        - A94
    documentType141B:
      name: documentType
      in: query
      description: The document type describes the principal characteristic of the document. For each data item this value might change
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A71
    processType141B:
      name: processType
      in: query
      description: The process type identifies the type of processing to be carried out on the information. For each data item this value might change.
      required: true
      style: form
      explode: true
      schema:
        type: string
        enum:
        - A33
    periodStart:
      name: periodStart
      in: query
      description: Time is always expressed in UTC. Pattern is yyyyMMddHHmm
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: "201601010000"
    periodEnd:
      name: periodEnd
      in: query
      description: Time is always expressed in UTC. Pattern is yyyyMMddHHmm
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: "201601010000"
  examples:
    GL_MarketDocument:
      value:
        xmlns: urn:iec62325.351:tc57wg16:451-6:generationloaddocument:3:0
        mRID: 0333ff4c65a847279e71ac5aabe1485e
        revisionNumber: "1"
        type: A65
        process.processType: A16
        sender_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        sender_MarketParticipant.marketRole.type: A32
        receiver_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        receiver_MarketParticipant.marketRole.type: A39
        createdDateTime: 2016-03-30T10:45:36Z
        time_Period.timeInterval:
          start: 2015-12-31T23:00Z
          end: 2016-12-31T23:00Z
        Timeseries:
          $ref: '#/components/examples/Timeseries14.1.B'
    GL_MarketDocument2:
      $ref: '#/components/examples/test'
    Acknowledgement_MarketDocument_400:
      value:
        xmlns: urn:iec62325351:tc57wg16:451-1:acknowledgementdocument:7:0
        mRID: be3917c7-0704-4
        createdDateTime: 2016-03-30T10:45:36Z
        sender_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        sender_MarketParticipant.marketRole.type: A32
        receiver_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        receiver_MarketParticipant.marketRole.type: A39
        received_MarketDocument.createdDateTime: 2016-03-30T10:45:35Z
        Reason:
          code: "999"
          text: Invalid query attributes or parameters
    Acknowledgement_MarketDocument_401:
      value:
        xmlns: urn:iec62325351:tc57wg16:451-1:acknowledgementdocument:7:0
        mRID: be3917c7-0704-4
        createdDateTime: 2016-03-30T10:45:36Z
        sender_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        sender_MarketParticipant.marketRole.type: A32
        receiver_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        receiver_MarketParticipant.marketRole.type: A39
        received_MarketDocument.createdDateTime: 2016-03-30T10:45:35Z
        Reason:
          code: "999"
          text: Unauthorized. Missing or invalid security token
    Acknowledgement_MarketDocument_429:
      value:
        xmlns: urn:iec62325351:tc57wg16:451-1:acknowledgementdocument:7:0
        mRID: be3917c7-0704-4
        createdDateTime: 2016-03-30T10:45:36Z
        sender_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        sender_MarketParticipant.marketRole.type: A32
        receiver_MarketParticipant.mRID:
          codingScheme: A01
          v: 10X1001A1001A450
        receiver_MarketParticipant.marketRole.type: A39
        received_MarketDocument.createdDateTime: 2016-03-30T10:45:35Z
        Reason:
          code: "-"
          text: Too many requests - max allowed 400 per minutes from each unique IP
    Timeseries14.1.B:
      value:
      - mRID: "1"
        businessType: A04
        objectAggregation: A01
        outBiddingZone_Domain.mRID:
          codingSchema: A01
          v: 10YCZ-CEPS-----N
        quantity_Measure_Unit.name: MAW
        curveType: A01
        period:
          timeInterval:
            start: 2015-12-31T23:00Z
            end: 2015-12-31T23:00Z
          resolution: PT60M
          Point:
          - position: 1
            quantity: 100
          - position: 2
            quantity: 100
          - position: '...'
            quantity: '...'
          - position: 540
            quantity: 100
      - mRID: "2"
        businessType: A04
        objectAggregation: A01
        outBiddingZone_Domain.mRID:
          codingSchema: A01
          v: 10YCZ-CEPS-----N
        quantity_Measure_Unit.name: MAW
        curveType: A01
        period:
          timeInterval:
            start: 2015-12-31T23:00Z
            end: 2015-12-31T23:00Z
          resolution: PT60M
          Point:
          - position: 1
            quantity: 100
          - position: 2
            quantity: 100
          - position: '...'
            quantity: '...'
          - position: 540
            quantity: 100
    test: {}
